.DEFAULT_GOAL := build

.PHONY:fmt vet build run-example
fmt:
	go fmt ./...
vet: fmt
	go vet ./...
	staticcheck ./...
	govulncheck ./...
build: vet
	go build -o bin/ ./...
run-example:
	./bin/wikipedia-pagerank /wiki/Computer_science
