.DEFAULT_GOAL := build

.PHONY:fmt vet build build-vet run-example build-run
fmt:
	go fmt ./...
vet: fmt
	go vet ./...
	staticcheck ./...
	govulncheck ./...
build:
	go build -o bin/ ./...
build-vet: vet
	go build -o bin/ ./...
run-example:
	./bin/wikipedia-pagerank /wiki/Computer_science
build-run: build-vet run-example
